# Generated by Django 5.1.3 on 2024-12-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comm',
        ),
    ]
