# Generated by Django 5.1.4 on 2024-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_rename_post_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
